namespace: rabbitmq

stack:
  defines: process-group
  runnable-list:
    - rabbitmq/rabbitmq
    - rabbitmq/nginx
  variables:
    rabbitmq-image-tag: "3.10-management"
    nginx-listen-port: 8081
    nginx-image-tag: "latest"
    rabbitmq-server-name: "rabbitmq.example.com"
    rabbitmq-node-port: 5672