namespace: mattermost-preview

stack:
  defines: process-group
  runnable-list:
    - rabbitmq/rabbitmq
  variables:
    rabbitmq-secure-password:
      type: string
      value: "yes"
    rabbitmq-image-tag: "3.10-management"


