namespace: rabbitmq

stack:
  defines: process-group
  runnable-list:
    - rabbitmq/rabbitmq
  variables:
    defines: variables
    rabbitmq-image-tag: 
       type: string
       value: "3.10-management"