namespace: rabbitmq-persistent-volume

stack:
  defines: process-group
  runnable-list:
    - rabbitmq-persistent-volume/rabbitmq
    - rabbitmq-persistent-volume/nginx
  variables:
    rabbitmq-image-tag: "3.10-management"
    nginx-listen-port: 80
    nginx-image-tag: "latest"
    rabbitmq-server-name: "rabbitmq.example.com"
    rabbitmq-node-port: 15672
    persistent-volume-disk-size: 10
    persistent-volume-disk-kind: HDD